//Game data types
export const SET_GAMES_DATA = "SET_GAMES_DATA";
export const FETCHING_GAMES_DATA = "FETCHING_GAMES_DATA";
export const FETCHING_GAMES_DATA_ERROR = "FETCHING_GAMES_DATA_ERROR";
export const RESET_GAME_DATA = "RESET_GAME_DATA";

//Active properties types
export const SET_ACTIVE_GAME_NAME = "SET_ACTIVE_GAME_NAME"
export const SET_ACTIVE_GAME_ID = "ACTIVE_GAME_ID"
export const SET_ACTIVE_NO_OF_LEVELS = "ACTIVE_NO_OF_LEVELS"
export const SET_ACTIVE_CURRENT_LEVEL = "ACTIVE_CURRENT_LEVEL"
export const SET_ACTIVE_LEVEL_ID = "SET_ACTIVE_LEVEL_ID"
export const SET_CURRENT_SCORE = "SET_CURRENT_SCORE"
export const SET_GAME_START_TIME = "SET_GAME_START_TIME"

//Auth types
export const SET_TOKEN = "SET_TOKEN"
export const SET_USER_ID = "SET_USER_ID"
export const SET_EMAIL_ID = "SET_EMAIL_ID"
export const REMOVE_TOKEN = "REMOVE_TOKEN"
export const REMOVE_USER_ID = "REMOVE_USER_ID"
export const REMOVE_EMAIL_ID = "REMOVE_EMAIL_ID"
export const FETCH_FROM_ASYNC_STORAGE = "FETCH_FROM_ASYNC_STORAGE"

//LevelIds of All Games 
export const SET_LEVEL_IDS = "SET_LEVEL_IDS"
export const FETCHING_LEVEL_IDS = "FETCHING_LEVEL_IDS"
export const FETCHING_LEVEL_IDS_ERROR = "FETCHING_LEVEL_IDS_ERROR"

//Session types 
export const SET_SESSION_COUNT = "SET_SESSION_COUNT"
export const UPDATE_SESSION_COUNT = "UPDATE_SESSION_COUNT"
export const FETCHING_SESSION_COUNT = "FETCHING_SESSION_COUNT"
export const FETCHING_SESSION_ERROR = "FETCHING_SESSION_ERROR"

//HighestScore types 
export const SET_HIGHEST_SCORES = "SET_GAME_BEST_SCORE"
export const FETCHING_HIGHEST_SCORES = "FETCHING_GAME_BEST_SCORE"
export const FETCHING_HIGHEST_SCORES_ERROR = "FETCHIN_GAMES_BEST_SCORES_ERROR"

//QuestionData types 
export const ADD_QUESTION_DATA = "ADD_GAME_DATA"
export const FETCH_QUESTION_DATA = "FETCH_GAME_DATA"
export const FETCH_QUESTION_DATA_ERROR = "FETCH_GAME_DATA_ERROR"

//Haptic and sound types 
export const FETCH_HAPTIC_AND_SOUND = 'FETCH_HAPTIC_AND_SOUND';
export const SET_HAPTIC_AND_SOUND = 'SET_HAPTIC_AND_SOUND';
export const FETCH_HAPTIC_AND_SOUND_ERROR = 'FETCH_HAPTIC_AND_SOUND_ERROR';
export const SET_SOUND_ENABLED = "SET_SOUND_ENABLED"
export const SET_HAPTIC_ENABLED = 'SET_HAPTIC_ENABLED';

//All levels
export const SET_ALL_LEVELS_DATA = "SET_ALL_LEVELS_DATA"
export const FETCH_ALL_LEVELS = "FETCH_ALL_LEVELS"
export const FETCH_ALL_LEVELS_ERROR = "FETCH_ALL_LEVELS_ERROR"
export const SET_NUMBER_OF_QUESTIONS_DATA = "SET_NUMBER_OF_QUESTIONS_DATA"

//current session
export const STORE_SESSION_SCORE = 'STORE_SESSION_SCORE';

//total day session score 
export const SET_INITIAL_ARRAY = "SET_INITIAL_ARRAY"
export const UPDATE_SESSION_SCORE = "UPDATE_SESSION_SCORE"

//rank reducer 
export const SET_RANK_ARRAY = "SET_RANK_ARRAY"
export const FETCH_RANK_ERROR = "FETCH_RANK_ERROR"
export const FETCH_RANK = "FETCH_RANK"
export const TIME_OF_UPDATE = "TIME_OF_UPDATE"

